[package]
name = "dirs-c"
version = "0.1.0"
edition = "2021"

[lib]
name = "dirs"
crate-type = ["cdylib", "staticlib"]

[dependencies]
dirs = "5.0.1"
libc = "0.2.153"
paste = "1.0.14"

# Optimize for size
[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

